theme: jekyll-theme-minimal
title: The Head Cheese
author: Sweiessekarte
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will explain how the Head Cheese Thinks and will be an awesome git work.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
