stheme: jekyll-theme-minimal
title: The Head Cheese
author: Sweiessekarte
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will explain how the Head Cheese Thinks and will be an awesome git work.

# social links
github_username:  Sweissekarte
paginate: 5 # amount of posts to show
paginate_path: /page:num/
show_excerpts: false # set to false to remove excerpts on the homepage
